### ISSUE TITLE
AI Girl, bug with sliders in character editor.

### ISSUE THREAD

**Issue by darkryder9** [IllusionMods/BepisPlugins#100]
Hi when im editing my girls in character editor I get some pretty big bugs.
when adjusting sliders the nose and/or chin will gets distorted to the left a quick save reload is a temp solution for this but annoying because it happens often. 
when loading characters the nose mouth and cheek depth/projection sliders dont seem to hold right postion, i have to +1 -1 on a slider for it move to the right postion. 
![Untitled3](https://user-images.githubusercontent.com/61544949/75443129-c3689480-592e-11ea-997d-3ac1a31f205e.png)
![Untitled](https://user-images.githubusercontent.com/61544949/75443134-c6fc1b80-592e-11ea-848c-634095fc3e00.png)
![Untitled1](https://user-images.githubusercontent.com/61544949/75443136-c794b200-592e-11ea-8d6c-5e2954661c84.png)

**Comment by ManlyMarco** [comment]
Check if the error happens with all orange sliders at their default values. If not, then it's an ABMX bug.

**Comment by darkryder9** [comment]
yeah it seems the orange sliders are bugged for me. i reset all the orange sliders and the character aren't distorting and they load up proper now.

**Comment by ManlyMarco** [comment]
In that case please post the issue to https://github.com/ManlyMarco/ABMX
Note that this is a long known issue with no fix. Someone is creating an update to ABMX so it might be best to wait and see if the bug still persists in it.
