### ISSUE TITLE
[AI-Shoujo] - [Problem with hair sliders in character editor]

### ISSUE THREAD

**Issue by user375s** [IllusionMods/BepisPlugins#101]
**Describe the bug**
- What game you are running.
**AI Shoujo**

When doing hair settings in character editor, the ‘reset all’ function doesn’t work anymore. Nothing happens when I click it, the hair slider value won’t return to its default value.

Also whenever I load a character, the hair slider is also broken. As you can see in the screenshot  below, the sliders have different value but they are all in the same position.

The problem doesn't exist when I disable AI_SliderUnlocker.dll
I'm using BepisPlugins r13.1.1

![4645](https://user-images.githubusercontent.com/35452463/77220305-6b116500-6b71-11ea-8b69-346739de51d4.png)

**To Reproduce**
1. Go to Character Editor.
2. Load a character card. Try to find a character who has variable values on its hair settings.
3. Go to hair settings, then open the 'Adjust' tab (the right most).
4. You will find that even when each sliders has different value, they're all in the same position.
5. Try to move around the sliders.
6. Try to click the 'Reset All' button. The sliders stay the same, the sliders don't return to its default value.

**Expected behavior**
* The sliders position should match its numerical value.
* After clicking the 'Reset All' button, sliders value and position should return to its default.

**Comment by ManlyMarco** [comment]
I can't reproduce the issue, everything works fine with latest release. Send the card that you are trying to load if it's only happening with some specific cards, and send your output_log.txt file from game dir.

**Comment by user375s** [comment]
Thanks. Here's the log file:

[output_log.txt](https://github.com/IllusionMods/BepisPlugins/files/4365119/output_log.txt)

**Comment by ManlyMarco** [comment]
Nothing obvious, it might be some weird interaction with another plugin/mod. It works fine in HF Patch v2.0 so with everything up to date.

**Comment by user375s** [comment]
I think I'm just gonna disable SliderUnlocker for now since I don't really use it that much. 

I'm having trouble identifying what plugins/mod cause this but I'm worried if I start again installing the game from scratch it might cause worse problems.

I'll download HF Patch v2 in case I might need it to repair my game in the future.

Thanks for your help!
