### ISSUE TITLE
[Koikatsu Party] [BGM Loader doesn't work]

### ISSUE THREAD

**Issue by Irgendeina** [IllusionMods/BepisPlugins#103]
I placed the Custom BGMS with the right names in the BGM file (BePiNex/Plugins/BGM). However it is still the original Audio.

**Comment by ManlyMarco** [comment]
Please send your output_log.txt and one of the files that doesn't work.

**Comment by Irgendeina** [comment]
[output_log.txt](https://github.com/IllusionMods/BepisPlugins/files/4520910/output_log.txt)

**Comment by Irgendeina** [comment]
[BGMLoader.dll.txt](https://github.com/IllusionMods/BepisPlugins/files/4520972/BGMLoader.dll.txt)

**Comment by ManlyMarco** [comment]
Looks like your ogg file is in an unusual format. Reconvert it into a simple single-track .ogg file and try again.

**Comment by Irgendeina** [comment]
It worked. Thank you ^^
