### ISSUE TITLE
HoneySelect 2 DX - Extended Save Plugin Data Load Fails Intermittently

### ISSUE THREAD

**Issue by OrangeSpork** [IllusionMods/BepisPlugins#125]
**Describe the bug**
- What game you are running.
- A clear and concise description of what the bug is.
- If you can, add any exceptions/errors you see in your output_log.txt or BepInEx console that might be related to the issue. You might be asked to send the whole log file if there's not enough information.
- Add screenshots if you think they will make it easier to explain.
Honey Select 2 DX (occurred on HS2 normal as well)

Long running issue I tripped over the cause of working on a plugin. I've noticed for a while that occasionally plugins wouldn't 'fire' when loading characters. Simply reloading the character usually took care of the issue, and multiple reloads always worked eventually, so it was just an aggravation. 

Found the problem working on my plugin, which inexplicably came up with no plugin data found even though I knew the character card had plugin data. Hitting load again caused it to find the plugin data on the second attempt.

Did some digging and traced the issue to the backing WeakDictionary for ExtendedSave. Somehow the save data is being removed (GC'd?) out of the dictionary between the load and the plugin CharaCustomFunctionControllers attempting to process the OnReload events and snag that sweet, sweet data.

I'm not sure if there's a really subtle error in the WeakDictionary implementation or if somehow the ChaFile stored in there isn't the one the plugins are getting...yet still works for the lookup most of the time??? Yeah, not sure there.

However, if I replace the cleanup purge function with a trailing sweep via 5 second delayed Coroutine...problem goes away. Absolutely reliable loads, 100% of the time. So definitely the issue, even if the mechanics evade me...

**To Reproduce**
I think you need enough cards to drag the loading process out long enough to make GC of the dictionary an issue...and enough CPU cores that Unity has processor available to do so.
Then you need a card that has obvious plugin mods to notice the issue (ABMX, Material Overlay and Skin Overlays for example).
Then reload and a bit of luck. I have the issue about 1 time in 10, though it is a bit streaky. 

**Expected behavior**
Plugins get extended data for the card when present.

Following code solves issues, but is rather brute force...ReaperRunner is just an empty MB to use as Coroutine fodder. I can put in a PR if desired...

 private UnityEngine.GameObject reaperRunnerObject;

        public void Set(TKey key, TValue value)
        {
            _items[new HashedWeakReference(key)] = value;            

            if (reaperRunnerObject == null)
            {
                reaperRunnerObject = new UnityEngine.GameObject();
                reaperRunnerObject.isStatic = true;
                ReaperRunner reaper = reaperRunnerObject.AddComponent<ReaperRunner>();
                reaper.StartCoroutine(PurgeKeys());
                
            }
        }

        IEnumerator PurgeKeys()
        {
            yield return new UnityEngine.WaitForSeconds(5);

            // Naive O(n) key prune
            var deadKeys = _items.Keys.Where(reference => !reference.IsAlive).ToList();
            foreach (var reference in deadKeys)
            {
                _items.Remove(reference);
            }

            UnityEngine.Object.Destroy(reaperRunnerObject);
        }

**Comment by ManlyMarco** [comment]
Thank you for figuring this out!

It's indeed very weird, looking at the code the only way for the key to be removed is if the reference is dead, but clearly the plugins are clearly getting a strong reference to this object after the fact, so it's like the purge runs before the object is fully created. https://github.com/IllusionMods/BepisPlugins/blob/master/src/Shared/WeakKeyDictionary.cs#L18

Did you try making the weak references into long weak references here? https://github.com/IllusionMods/BepisPlugins/blob/master/src/Shared/HashedWeakReference.cs#L13
More info about short/long references here: https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/weak-references

**Comment by OrangeSpork** [comment]
The resurrection aware long weak reference resulted in no change is behaviour, problem still occurs.

The ThreadingHelper was handy, simplifies the Coroutine delayed reaper approach nicely. 

Found another option if you prefer, swapping the backing weak reference key dictionary to the shiny new ConditionalWeakTable see https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.conditionalweaktable-2?view=net-5.0 which appears to be the official implementation/solution for this works as well.

The catch (...sigh, of course...) is that it's only available in .Net frameworks 4+, so the older (HS, KK, EC, PH) apps can't use it. However, I've not heard of them being affected by this either? I've only seen the issue with HS2 and AI, so assuming those are the only affected versions, ConditionalWeakTable can selectively replace the current implementation with a bit of preprocessor directive fun...

I can put a PR in for either approach (Coroutine or ConditionalWeakTable) if you have a preference?

**Comment by ManlyMarco** [comment]
Yeah, it doesn't seem to be an issue in older games. I'm split between the two approaches, I'd probably be fine with implementing either one you make a PR for. Coroutine approach would cover old game versions in case that it can happen and it would keep things consistent, while the WeakTable would be more optimal but add separate code paths.

**Comment by ManlyMarco** [comment]
Fixed in #126
