### ISSUE TITLE
Release ZIPs have backslash paths, but forward slashes are better

### ISSUE THREAD

**Issue by danbulant** [IllusionMods/BepisPlugins#131]
The ZIPs have files with backslash paths (because someone writing DOS thought it was a good idea to use that), but those have their own issues, and generally, forward slashes (`/`) are more portable and have less issues.

Not sure why is that the case, default ZIP maker in windows does use forward slashes.

Found that when I had to rename all the files because I tried to use them on linux (via wine).
![image](https://user-images.githubusercontent.com/30036876/126049110-53910aff-66a1-4ebc-b59d-0373bf48b49c.png)

Doesn't impact windows users (until someone tries to use a software with badly written code), but fixing this shouldn't be a problem either and it will make life easier for others.

**Comment by ManlyMarco** [comment]
There's no easy way of fixing it outside of not using the built in powershell compression methods (we tried), but that would make the repository less portable, and it would be a mess to implement since all of our repositories use this method of release creation.

**Comment by danbulant** [comment]
Oh sorry then. Kinda sucks that builtin powershell compression uses this (non-standard) way while their explorer compression uses normal one....

**Comment by ManlyMarco** [comment]
@Mantas-2155X made some sort of a script for opening these archives on linux so maybe he can share.

**Comment by ManlyMarco** [comment]
Sounds like he lost the script, what it did was take some files with slashes in their names and put them in proper subdirectories.

**Comment by GeBo1** [comment]
You can force update the powershell archive module to get the fix for this

```
Install-Module Microsoft.PowerShell.Archive -MinimumVersion 1.2.3.0 -Repository PSGallery -Force -AllowClobber
```

**Comment by Mantas-2155X** [comment]
@danbulant I see you're using KDE, are you also using ark or a different app to extract archives?
In a later version of ark (can be installed by using kubuntu-backports ppa) they added support for extracting backslash paths so this is no longer an issue for KDE users, not sure about other DEs and their default apps.

Would still be good if the powershell script was fixed to use forwardslashes to avoid this problem altogether.

**Comment by danbulant** [comment]
> In a later version of ark (can be installed by using kubuntu-backports ppa) they added support for extracting backslash paths so this is no longer an issue for KDE users, not sure about other DEs and their default apps.

I'm on Manjaro so I should have latest KDE and ark installed. I can't even try that as PPAs are Debian thing which isn't compatible with Arch.

**Comment by Mantas-2155X** [comment]
Maybe you could try building ark from source? 
Looks like currently the ark version from kubuntu-backports is 21.08.0 and it does not have the issue.

**Comment by danbulant** [comment]
Oh right I don't have the issue anymore as well (21.08.0-1), so guess they did fix it since I last tried installing it (I created the issue but didn't try the ZIPs since). Last release can be opened correctly.

Last release started using normal forward slashes though, so that fixes it too. 16.5. has forward slashes, the one I tried before (16.3.1) had backwards.

```
❯ unzip -l ./KK_BepisPlugins_r16.5.zip
Archive:  ./KK_BepisPlugins_r16.5.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2021-08-29 09:57   BepInEx/plugins/
     7680  2021-08-29 09:57   BepInEx/patchers/KK_ExtensibleSaveFormat_Patcher.dll
    15872  2021-08-29 09:57   BepInEx/plugins/KK_BepisPlugins/BGMLoader.dll
    16896  2021-08-29 09:57   BepInEx/plugins/KK_BepisPlugins/ColorCorrector.dll
    17408  2021-08-29 09:57   BepInEx/plugins/KK_BepisPlugins/ConfigurationManagerKK.dll
    46080  2021-08-29 09:57   BepInEx/plugins/KK_BepisPlugins/ExtensibleSaveFormat.dll
    14312  2021-08-29 09:57   BepInEx/plugins/KK_BepisPlugins/ExtensibleSaveFormat.xml
   200704  2011-01-03 14:16   BepInEx/plugins/KK_BepisPlugins/ICSharpCode.SharpZipLib.dll
    14848  2021-08-29 09:57   BepInEx/plugins/KK_BepisPlugins/InputUnlocker.dll
    81408  2021-08-29 09:57   BepInEx/plugins/KK_BepisPlugins/Screencap.dll
     7633  2021-08-29 09:57   BepInEx/plugins/KK_BepisPlugins/Screencap.xml
   128512  2021-08-29 09:57   BepInEx/plugins/KK_BepisPlugins/Sideloader.dll
    30251  2021-08-29 09:57   BepInEx/plugins/KK_BepisPlugins/Sideloader.xml
    31232  2021-08-29 09:57   BepInEx/plugins/KK_BepisPlugins/SliderUnlocker.dll
---------                     -------
   612836                     14 files
❯ unzip -l ./KK_BepisPlugins_r16.3.1.zip
Archive:  ./KK_BepisPlugins_r16.3.1.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2021-05-31 03:09   BepInEx\plugins\
    15872  2021-05-31 03:09   BepInEx\plugins\KK_BepisPlugins\BGMLoader.dll
    16896  2021-05-31 03:09   BepInEx\plugins\KK_BepisPlugins\ColorCorrector.dll
    17408  2021-05-31 03:09   BepInEx\plugins\KK_BepisPlugins\ConfigurationManagerKK.dll
    39936  2021-05-31 03:09   BepInEx\plugins\KK_BepisPlugins\ExtensibleSaveFormat.dll
    14084  2021-05-31 03:09   BepInEx\plugins\KK_BepisPlugins\ExtensibleSaveFormat.xml
   200704  2011-01-03 14:16   BepInEx\plugins\KK_BepisPlugins\ICSharpCode.SharpZipLib.dll
    14848  2021-05-31 03:09   BepInEx\plugins\KK_BepisPlugins\InputUnlocker.dll
    81408  2021-05-31 03:09   BepInEx\plugins\KK_BepisPlugins\Screencap.dll
   128512  2021-05-31 03:09   BepInEx\plugins\KK_BepisPlugins\Sideloader.dll
    29998  2021-05-31 03:09   BepInEx\plugins\KK_BepisPlugins\Sideloader.xml
    31232  2021-05-31 03:09   BepInEx\plugins\KK_BepisPlugins\SliderUnlocker.dll
---------                     -------
   590898                     12 files
```

so that also fixes this issue.
