### ISSUE TITLE
Koikatu - KKAPI 1.21, 1.22 and BepInEx 5.4.15 error compiling plugin for Koikatu

### ISSUE THREAD

**Issue by IDontHaveIdea** [IllusionMods/BepisPlugins#134]
I'm using reference in VS2019.  (https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)

When using references to BepInEx 5.4.15 and KKAPI 1.21 (1.22 is the same) I get the error:

Error	CS0246	The type or namespace name 'KKAPI' could not be found (are you missing a using directive or an assembly reference?)

I am using package references with Visual Studio 2019.  

- KKAPI 1.22 with BepInEx 5.4.13 works fine using PackageRefernce. 
- If the plugin uses BepInEx 5.4.15 and the project references BepInEx.Harmony you get the error BepInEx.Harmony not found.
- Using a reference to HarmonyLib instead of BepInEx.Harmony seems to work ok if not using KKAPI.

I noticed that the nuget package for BepInEx.Harmony 2.5.4 the lib directory **<ins>does not have BepInEx.Harmony.dll**</ins>, prior versions do. I think this is the problem.

Just adding a direct reference to the KKAPI.dll solves the issue and I'm able to compile a functional plugin.

**Comment by ManlyMarco** [comment]
This isn't really a bug, the code is simply still using obsolete members that are no longer supported. Just use Harmony.CreateAndPatchAll instead or wait for someone else to update the source (it might take some time).

**Comment by IDontHaveIdea** [comment]
My mistake I did not change the label.

Is more a question of is ok for the BepInEx 2.5.4 to not have the BepInEx.Harmony.dll.

Thanks for the prompt response.

**Comment by ManlyMarco** [comment]
The dll is still in the release, but I stopped including it in the repository to force move to the new API.
