### ISSUE TITLE
[Honey Select2 Studio] - [screenshot with upsampling will disable the depth of field blur effect]

### ISSUE THREAD

**Issue by lyfllrr** [IllusionMods/BepisPlugins#137]
**Describe the bug**
- In Honey Select2 Studio, if screenshot taken with upsampling or with the the height and width value bigger than display's resolution, the screenshot will lose Depth of filed blur effect.
- eg. my display's resolution is 2560*1440, and if I set the height with 2160 and widh with 3840, and take a screenshot, then the Depth of field blur effect will be disabled in that shot.
 
**To Reproduce**
1. Open Honey Select2 Studio
2. Add any thing into the studio as the blur effect test target
3. Open System -> 画面効果(video effect) -> 被写界深度(Depth of field)
4. Check the radio of Depth of field and set the value as you can see the blur effect easily.
5. Press F1 and open Screenshot Manager 16.7.1
6. Set 'Upsampling ratio' bigger than 1
7. Take a screenshot  

**Expected behavior**
The blur effect of Depth of field should be captured in screenshot.

**Comment by OrangeSpork** [comment]
This is not an issue with the screen cap mod and isn't fixable. The Unity DoF post processing effect in this version of Unity does not support render resolutions different from the display resolution.
