### ISSUE TITLE
[Koikatsu Sunshine] - [No mods will load in VRTheater (11/19 update tool for Koikatsu Sunshine)]

### ISSUE THREAD

**Issue by ghost** [IllusionMods/BepisPlugins#147]
## Before submitting
- Update to latest BepisPlugins and supported version of BepInEx.
- Update your game to latest version.
- Make sure no other plugins are crashing or having issues (remove them for testing and see if your issue is fixed.)

**Describe the bug**
- Koikatsu Sunshine 11/19 update w/ HF Patch v1.3
- No mods will load in the VRTheater tool.
- Over 130 issues, posted output log below.
- Screenshot shown below.

**To Reproduce**
1. Open VRTheater.exe
2. See no mod is able to be loaded.

**Expected behavior**
Expected mods to function and to be able to view scenes with modded assets from HF Patch.
[output_log.txt](https://github.com/IllusionMods/BepisPlugins/files/7572245/output_log.txt)
![unknown](https://user-images.githubusercontent.com/20508261/142673092-7a4469ba-31b8-49be-beb6-1f10f0c553cd.png)

**Comment by ManlyMarco** [comment]
It's known, nothing at the moment supports VRTheater and there's no plans to fix it since there's already a studio VR plugin.
