### ISSUE TITLE
[Koikatsu Sunshine] - [DialogueBug]

### ISSUE THREAD

**Issue by Leshiy1** [IllusionMods/BepisPlugins#148]
When I talk to the characters after a while, approaching the next character after pressing the button to start the dialogue, a bug appears randomly in which the entire interface disappears and the characters just silently stand in front of each other, while nothing can be done the game does not respond to pressing buttons other than exiting the game and opening the menu on F1

**Comment by ManlyMarco** [comment]
Are you sure it's a bug in BepisPlugins? Try narrowing down which plugin causes it, removing BepisPlugins will disable pretty much all plugins so it doesn't give useful info. Post your output_log after you narrow it down some more.

**Comment by FPK997** [comment]
I also encountered the same, but the characters with fixed personalities will get stuck

**Comment by FPK997** [comment]
To correct, I delete KoikatsuSunshine_Data and abdata and replace the original files, but it is recommended to backup first

**Comment by ManlyMarco** [comment]
In that case it's because of bad game files. Some of the partial official patches had issues like this, to fix you need to apply the latest full official patch.
