### ISSUE TITLE
[KK/KKS Screenshot manager] - [Left and right eye replacement in 3D capture.]

### ISSUE THREAD

**Issue by leoftm** [IllusionMods/BepisPlugins#149]
The 3D left-right capture in Screenshot Manager is currently for "cross-eyed viewing", which means that the left side is for the right eye and the right side is for the left eye.
It's easy to swap between the two when it's just an image, but when combined with VideoExport, it becomes quite cumbersome.
Cross-eyed viewing is the standard for stereoscopic viewing with the naked eye, but side-by-side (parallel viewing) is the standard for stereoscopic video.
Therefore, I would like to have a mode to capture left and right images by swapping them.

**Comment by ManlyMarco** [comment]
Try this build, added new setting for eye flipping. [test.zip](https://github.com/IllusionMods/BepisPlugins/files/7651907/test.zip)

**Comment by leoftm** [comment]
Thanks for the quick response!
I replaced "Koikatu\BepInEx\plugins\KK_BepisPlugins\Screencap.dll" and started CharaStudio, but ctrl+F11, alt+F11, and shift+F11 resulted in a normal capture.
Isn't this function called from "Screenshot Manager 16.9.1"?

(I haven't tried KKS_Screencap.dll yet, I tried the KK version anyway.)

**Comment by ManlyMarco** [comment]
Change the config setting first.

**Comment by leoftm** [comment]
![CharaStudio_dtp_211204091546_003286x](https://user-images.githubusercontent.com/39472846/144688679-2f8600b4-349a-47a1-a50e-41b04c510081.png)
When replacing "Koikatu\BepInEx\plugins\KK_BepisPlugins\Screencap.dll"
For some reason, the "Open Settings Window (
F11+Left Shift)" does not open the "Screenshot Settings" window, which used to be able to open.

**Comment by ManlyMarco** [comment]
Thanks, fixed the issue
[Screencap.zip](https://github.com/IllusionMods/BepisPlugins/files/7654310/Screencap.zip)

**Comment by leoftm** [comment]
Thanks, that's very helpful!
Please release a patched version of the KKS version even when it is convenient, as I am experiencing the same symptoms.

**Comment by leoftm** [comment]
Addendum
Timeline animation is not applied to cameras installed with the December 5, 2021 version of screencap.dll.
When I place a camera in the workspace, select it from the cameras currently installed, and animate it on the timeline, if I check the 3D checkbox, for some reason only the first frame is captured in the animation position, and the second and subsequent frames are moved to the position of the camera that is not installed.
If I do not select 3D, it seems to work fine.

Translated with www.DeepL.com/Translator (free version)

**Comment by ManlyMarco** [comment]
Opened a separate issue for the timeline issue #150

**Comment by Gaga123s** [comment]
Why the new version render picture png longer than the old version. When i press F11 screenshot, the game abit lag but the picture comeout right in sec. Its usefull when take multip pictures frame.
New version smoother when press F11, but render each pict 5sec for 1. spam F11 will filled with "screenshot taken" but only 2-3 of it.

**Comment by ManlyMarco** [comment]
@Gaga123s Please open a separate issue and use clearer language to explain the issue. Provide screenshots to show it as well.
