### ISSUE TITLE
Discussion Bug With the Guide

### ISSUE THREAD

**Issue by MasterRikuHime** [IllusionMods/BepisPlugins#158]
When I talk to the guide, a bug appears in which the entire interface disappears and the characters just silently stand in front of each other ! I have that in my console : 
![image](https://user-images.githubusercontent.com/103380923/162632808-6ce1f11d-e562-4d51-9773-b88400ed003c.png)

And after leave the game :
![image](https://user-images.githubusercontent.com/103380923/162632861-2a72b13c-68e3-4ed0-99d3-a4b037967d05.png)

Thank you for your help !

**Comment by ManlyMarco** [comment]
Make sure all of your plugins are updated, this issue was fixed at some point but I don't remember what plugin caused it.
