### ISSUE TITLE
[KK] - Screencap compatibility with a PostProcessingEffects plugin

### ISSUE THREAD

**Issue by EveKaczmarek** [IllusionMods/BepisPlugins#165]
**BepInEx** - 5.4.19.0
**Screenshot Manager** - 18.2
**PostProcessingEffects** - 3.6.0.0

Something odd is happening when I'm trying to save the coordinates card and a PostProcessingEffects plugin is enabled. This scene getting stuck until the game restart, Screencap doesn't allows me to make any new screenshots and chara (re)loading is completely broken. Here's the error from log that appears there right after attempt to save the coordinates.

    NullReferenceException: Object reference not set to an instance of an object

    void PostProcessingEffectsV3.Patch2.Postfix()
    void Screencap.Hooks.DownscaleEncoded(byte[])
    void Screencap.Hooks.CreatePngPostfix(byte[])
    byte[] ChaCustom.CustomCoordinateFile.CreateCoordinatePng()
    bool ChaCustom.CustomCoordinateFile+<CreateCoordinateFileCoroutine>c__Iterator0.MoveNext()
    void UnityEngine.SetupCoroutine.InvokeMoveNext(IEnumerator, IntPtr)
 
    (Filename:  Line: -1)

![Koikatu_20220712_150743_olIC6CrBy5](https://user-images.githubusercontent.com/52298587/178490133-d9361a78-0226-4520-93d0-a28b31bdf451.png)

As a workaround, I've tried to disable effects in the plugin settings and card upsampling and it worked. If Card Image Upsampling Ratio is set to 1, everything works as expected.

**Comment by ManlyMarco** [comment]
It looks like a problem on the side of the PostProcessingEffects plugin, not screencap.

**Comment by EveKaczmarek** [comment]
I see. Well then, you can close the issue if nothing can be fixed on your side. Thanks.

**Comment by ManlyMarco** [comment]
Sorry I can't help, try reporting the issue to the maker of the other plugin.
