### ISSUE TITLE
KKS-Error when I open Studio from KKS

### ISSUE THREAD

**Issue by Solidsnake9058** [IllusionMods/BepisPlugins#167]
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'ExtensibleSaveFormat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
UnityEngine.GameObject:AddComponent()
HSPE.HSPE:LevelLoaded(Int32)
ToolBox.GenericPlugin:LevelLoaded(Scene, LoadSceneMode)
UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded(Scene, LoadSceneMode)

**Comment by ManlyMarco** [comment]
You probably installed a plugin for the wrong game or multiple game versions of a plugin.

**Comment by Solidsnake9058** [comment]
It's fixed after that update [IllusionFixes] to lastest.
