### ISSUE TITLE
[KK] - Timeline does not inherit Eyes/Mouth,L of blendshapes when changing characters.

### ISSUE THREAD

**Issue by leoftm** [IllusionMods/BepisPlugins#170]
Timeline does not inherit Eyes/Mouth,L of blendshapes when changing characters.

After loading a charastudio scene with blendshapes, some blendshapes are not inherited when changing the character.
The Eyes/Mouth,L key is present immediately after loading the scene and changing the character, but disappears the moment the timeline is moved.
Not sure if this is due to Timeline or KKPE, sorry if it is not a Timeline Issue.

The scene used for the sample is
https://discord.com/channels/447114928785063977/447116302096662528/1029445874146885753
(Note: In the video, the "Eyes/Mouth,L" key on the timeline is selected for clarity, but the problem also occurs when nothing is selected.)

https://user-images.githubusercontent.com/39472846/197362299-92253a6c-4372-4871-a9d9-d2e00bd0f81e.mp4

**Comment by ManlyMarco** [comment]
As far as I can see it's either a Timeline or KKPE issue. Can you post this issue here https://github.com/IllusionMods/HSPlugins/issues? That's where Timeline and KKPE are hosted.
