### ISSUE TITLE
[KK/HS2] - [SliderUnlocker] NullReferenceException

### ISSUE THREAD

**Issue by hamer** [IllusionMods/BepisPlugins#171]
Context:
* BepInEx v5.4.21
* BepisPlugins v19.0.2
* Steam versions of Koikatsu Party (with Afterparty DLC) and Honey Select 2 Libido DX

SliderUnlocker is quite useful plugin especially on Steam versions of Illusion games as there are certain rectrictions on slider boudaries in character editor.

SliderUnlocker plugin seemed to work as it created config file, appeared in logs and ConfigurationManager. But it didn't affected sliders at all. The reason was unknown till log level was increased for invesigation and NullReferenceException found for exactly this plugin.

Reproduce steps are:
1. Install BepInEx
2. Put either `HS2_SliderUnlocker.dll` or `SliderUnlocker.dll` in `BepInEx/plugins/`
3. Increase a log level by changing *LogChannels* to *All* in `BepInEx/config/BepInEx.cfg`
4. Enable log redirection by changing *redirectOutputLog* to *true* in `doorstop_config.ini`
5. Launch the game and look in `output_log.txt` for NullReferenceException and/or verify sliders boundaries in chara editor.

Relevant part of HS2 log:
```
[Message:   BepInEx] BepInEx 5.4.21.0 - HoneySelect2 (23.10.2022 14:06:33)
[Info   :   BepInEx] Running under Unity v2018.4.11.7379119
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugins to load
[Info   :   BepInEx] Loading [Slider Unlocker 19.0.2]
...
NullReferenceException: Object reference not set to an instance of an object
  at SliderUnlocker.Hooks.InstallHooks () [0x0003b] in <8d6dd3de634c47e6b2136f5ed7869690>:0 
  at SliderUnlocker.SliderUnlocker.Awake () [0x00070] in <8d6dd3de634c47e6b2136f5ed7869690>:0 
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
```
And for KK:
```
[Message:   BepInEx] BepInEx 5.4.21.0 - Koikatsu Party (6/6/2019 7:17:17 AM)
[Info   :   BepInEx] Running under Unity v5.6.2.10654012
[Info   :   BepInEx] CLR runtime version: 2.0.50727.1433
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugins to load
[Info   :   BepInEx] Loading [Slider Unlocker 19.0.2]
...
NullReferenceException: Object reference not set to an instance of an object
  at SliderUnlocker.Hooks.InstallHooks () [0x00000] in <filename unknown>:0 
  at SliderUnlocker.SliderUnlocker.Awake () [0x00000] in <filename unknown>:0 
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
```

Full logs are available here:
* Just SliderUnlocker on KK: [output_log.txt](https://novychenko.kyiv.ua/illusion/Koikatsu%20Party/output_log.txt), [LogOutput.log](https://novychenko.kyiv.ua/illusion/Koikatsu%20Party/LogOutput.log);
* Just SliderUnlocker on HS2 [outout_log.txt](https://novychenko.kyiv.ua/illusion/HoneySelect2Libido%20DX/output_log.txt), [LogOutput.log](https://novychenko.kyiv.ua/illusion/HoneySelect2Libido%20DX/LogOutput.log);
* More plugins on KK [output_log.txt](https://novychenko.kyiv.ua/illusion/Koikatsu%20Party/Full/output_log.txt), [LogOutput.log](https://novychenko.kyiv.ua/illusion/Koikatsu%20Party/Full/LogOutput.log);
* More plugins on HS2 [outout_log.txt](https://novychenko.kyiv.ua/illusion/HoneySelect2Libido%20DX/Full/output_log.txt), [LogOutput.log](https://novychenko.kyiv.ua/illusion/HoneySelect2Libido%20DX/Full/LogOutput.log).

PS: I apologise for missing step regarding the updating the game before posting this issue. It is unclear whether the Steam versions of games needs to be updated and how exactly. But if so, please, tell it explicitly before closing the issue.

Is it possible to confirm that actual version of plugin works on Japanese versions of HS2 and KK well?

**Comment by ManlyMarco** [comment]
SliderUnlocker works on all game versions, the issue was because the game was updated to latest version by Steam. Most people use an older version, so the issue went under the radar for a while.
