### ISSUE TITLE
[HS2] - [Screenshotwithcharacard]Does character (F11 key) screenshot picture include the character card?

### ISSUE THREAD

**Issue by Fish-In-Dream** [IllusionMods/BepisPlugins#178]
Hi, my SSD is broken and I lost everything QAQ

I want to know can I get my character card back by a (F11 key) studio screenshot picture. It's 8K.

Link https://mega.nz/file/h5JUibxI#v6cKP3WGVNOJAWmoSuAB0356k6P0uUwVqbGYFRCJp0g

**Comment by ManlyMarco** [comment]
Screenshots don't include any data outside of the image.
