### ISSUE TITLE
BepisPlugins r19.2 Bloom BUG

### ISSUE THREAD

**Issue by HanYuanyi** [IllusionMods/BepisPlugins#181]
[BepisPlugins r19.2](https://github.com/IllusionMods/BepisPlugins/releases/tag/r19.2)

The Koikatu.exe is unable to enable Bloom. Whether you try to turn it on or off, Bloom remains inactive.

**Comment by ManlyMarco** [comment]
Did you try restarting the game after changing the setting?

**Comment by ManlyMarco** [comment]
Closing stale issue. Please reopen if anyone can reproduce the issue.
