### ISSUE TITLE
[KKS] - [Screencap 3D VR performance]

### ISSUE THREAD

**Issue by WelchYang** [IllusionMods/BepisPlugins#184]
Is there any way to increase the rendering speed?
I am using VideoExport plugin (based on screencap 360 screenshot to create KKS VR 3d videos), but it takes seven seconds to render only one frame with 4070ti, too slow.
Is there a way to improve the rendering speed, such as use unity’s merging algorithm(Single-pass instanced,Multi-pass maybe) instead of cpu algorithm, not using 360-degree images, changing to 180-degree images, using RenderTexture instead of Texture2D , and JPG reducing file size, and speeding up writing to hard disk

**Comment by ManlyMarco** [comment]
You definitely could do it faster but probably not with the same features, and definitely not with without increasing code complexity. If you're up to a challenge then go for it and submit a PR.

**Comment by WelchYang** [comment]
Including fixing the image stitching issue, Could I request you to make these changes and fix? I can pay you 20 dollars on paypal.

**Comment by WelchYang** [comment]
> 你肯定可以做得更快，但可能无法使用相同的功能，并且绝对不能在不增加代码复杂性的情况下完成。如果你愿意接受挑战，那就去挑战并提交PR。

I don’t have much knowledge about programming, but I found a modification method from zodgame that changes VR to 180°, but the view always stays on the horizon. I hope to make the view follow the camera movement.
------------

Change the output of method capture from Texture2D to RenderTexture.
Core.ScreenshotManager.cs
入れ替わりStitchImages
private static Texture2D CombineTexture180VR(RenderTexture left, RenderTexture right)
        {
            var result = new Texture2D(left.width, left.height, TextureFormat.ARGB32, false);
            RenderTexture temp = RenderTexture.active;
            RenderTexture.active = left;
            result.ReadPixels(new Rect(left.width / 4, 0, left.width / 2, left.height), 0, 0);
            RenderTexture.active = right;
            result.ReadPixels(new Rect(left.width / 4, 0, left.width / 2, left.height), left.width / 2, 0);
            RenderTexture.active = temp;
            RenderTexture.ReleaseTemporary(left);
            RenderTexture.ReleaseTemporary(right);
            return result;
        }

**Comment by WelchYang** [comment]
> You definitely could do it faster but probably not with the same features, and definitely not with without increasing code complexity. If you're up to a challenge then go for it and submit a PR.

I don’t have much knowledge about programming, but I found a modification method from zodgame that changes VR to 180°, but the view always stays on the horizon. I hope to make the view follow the camera movement.
------------

Change the output of method capture from Texture2D to RenderTexture.
Core.ScreenshotManager.cs
入れ替わりStitchImages
private static Texture2D CombineTexture180VR(RenderTexture left, RenderTexture right)
        {
            var result = new Texture2D(left.width, left.height, TextureFormat.ARGB32, false);
            RenderTexture temp = RenderTexture.active;
            RenderTexture.active = left;
            result.ReadPixels(new Rect(left.width / 4, 0, left.width / 2, left.height), 0, 0);
            RenderTexture.active = right;
            result.ReadPixels(new Rect(left.width / 4, 0, left.width / 2, left.height), left.width / 2, 0);
            RenderTexture.active = temp;
            RenderTexture.ReleaseTemporary(left);
            RenderTexture.ReleaseTemporary(right);
            return result;
        }

**Comment by WelchYang** [comment]
> You definitely could do it faster but probably not with the same features, and definitely not with without increasing code complexity. If you're up to a challenge then go for it and submit a PR.

I have not learned C# programming before, but I found a modification method from zodgame that changes VR to 180°, but the view always stays on the horizon. I hope to make the view follow the camera movement.
------------

Change the output of method capture from Texture2D to RenderTexture.
Core.ScreenshotManager.cs
入れ替わりStitchImages
private static Texture2D CombineTexture180VR(RenderTexture left, RenderTexture right)
        {
            var result = new Texture2D(left.width, left.height, TextureFormat.ARGB32, false);
            RenderTexture temp = RenderTexture.active;
            RenderTexture.active = left;
            result.ReadPixels(new Rect(left.width / 4, 0, left.width / 2, left.height), 0, 0);
            RenderTexture.active = right;
            result.ReadPixels(new Rect(left.width / 4, 0, left.width / 2, left.height), left.width / 2, 0);
            RenderTexture.active = temp;
            RenderTexture.ReleaseTemporary(left);
            RenderTexture.ReleaseTemporary(right);
            return result;
        }
