### ISSUE TITLE
HS2.targets a wrong version of BepInEx (5.4.22.0) 

### ISSUE THREAD

**Issue by goodmaney** [IllusionMods/BepisPlugins#196]
my BepInEx is 5.4.22.0,I try the  BepisPlugins  19.4 to 19.6. it report 
[Warning:   BepInEx] Plugin [BGM Loader 19.4] targets a wrong version of BepInEx (5.4.22.0) and might not work until you update
[Warning:   BepInEx] Plugin [Configuration Manager wrapper for HoneySelect 2 19.4] targets a wrong version of BepInEx (5.4.22.0) and might not work until you update
[Warning:   BepInEx] Plugin [Extended Save 19.4] targets a wrong version of BepInEx (5.4.22.0) and might not work until you update
[Warning:   BepInEx] Plugin [Input Length Unlocker 19.4] targets a wrong version of BepInEx (5.4.22.0) and might not work until you update
[Warning:   BepInEx] Plugin [Screenshot Manager 19.4] targets a wrong version of BepInEx (5.4.22.0) and might not work until you update
[Warning:   BepInEx] Plugin [Sideloader 19.4] targets a wrong version of BepInEx (5.4.22.0) and might not work until you update
[Warning:   BepInEx] Plugin [Slider Unlocker 19.4] targets a wrong version of BepInEx (5.4.22.0) and might not work until you update

**Comment by ManlyMarco** [comment]
Check the actual BepInEx version in your log. It's most likely out of date.
