### ISSUE TITLE
[HS2] - [About tattoo mod's color]

### ISSUE THREAD

**Issue by crazy-night** [IllusionMods/BepisPlugins#200]
I 'm following the tutorial on the wiki to make a texture mod. But I'm confused that colorful textures loses colors in the game. It seems that only two colors will remain. I'm wondering whether there is a rule about that. How can I make a colorful tattoo mod? p.s. I've known overslays but I prefer mod since it's convenient to adjust.

**Comment by ManlyMarco** [comment]
It depends on item category and what you set in your list files. Open existing zipmods and see how they are done or ask in the modding channel on the discord server.
