### ISSUE TITLE
can not edit game options with the plugin

### ISSUE THREAD

**Issue by monado1110** [IllusionMods/BepisPlugins#78]
hey guys i can't edit any game option in F1 menu everything resets, there's a weird plugin button on the right when i press F1 to open game option, for example if i turn on DOF and go back, DOF would be disable again. I can't not negative to other section like sound, graphics etc...either.
and i can't edit male transparent too, he's always blue, i want to change his color to something else

**Comment by ManlyMarco** [comment]
Please send your output_log.txt file after trying to change a setting and closing the game. It should be inside the _data folder of your game.

**Comment by monado1110** [comment]
> 
> 
> Please send your output_log.txt file after trying to change a setting and closing the game. It should be inside the *_data folder of your game.


i got this fixed by moving the game to another HDD, i don't know why but it actually worked.

**Comment by ManlyMarco** [comment]
Most likely file permissions were broken in some way that didn't allow the game to write to the config files.
