### ISSUE TITLE
is there a way to use reshade on the main game ?

### ISSUE THREAD

**Issue by monado1110** [IllusionMods/BepisPlugins#79]
i have tried both directx9 and directx10 but none worked, is there an extra step to install reshade while using BepisPlugins ?

**Comment by ManlyMarco** [comment]
Are you asking to apply reshade effects to the screenshots? That's not possible. If you can't get reshade to work at all then it's not related to bepisplugins at all.

**Comment by ManlyMarco** [comment]
You can definitely use reshade with the game, the setup is the same as with any other unity game. You can find many guides on how to do it online.
