### ISSUE TITLE
AI-Syoujyo Sideloader error

### ISSUE THREAD

**Issue by MangoJongo** [IllusionMods/BepisPlugins#80]
Does anyone know what the problem is?
It looks like I am the only one having this issue and I have no idea why.

[Info   :Sideloader] Scanning the "mods" directory...
[Info   :Sideloader] Loading mods from directory: H:\Downloads\AI girl\mods
[Error  :Sideloader] Failed to load archive "Sideloader Modpack\DeathWeasel\[DeathWeasel][AI]Birthmark.zipmod" with error: System.NotSupportedException: No data is available for encoding 775. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
  at System.Text.Encoding.GetEncoding (System.Int32 codepage) [0x001e3] in <f2e6809acb14476a81f399aeb800f8f2>:0 

Here is the full Log

[LogOutput.log](https://github.com/IllusionMods/BepisPlugins/files/3778944/LogOutput.log)

**Comment by kmuuk** [comment]
You are not alone. 
Turns out changing windows regional formatting to English fixed it for me and a few others.

**Comment by ManlyMarco** [comment]
Can you test if this still happens with these plugins? 
[test build.zip](https://github.com/IllusionMods/BepisPlugins/files/3786757/test.build.zip)

**Comment by MangoJongo** [comment]
Oh my god it works with those plugins!
