### ISSUE TITLE
Sideloader seems not working in AI Girl

### ISSUE THREAD

**Issue by Tidyzq** [IllusionMods/BepisPlugins#82]
BepInEx version: 5.0.0.165
Sideloader version: 12.3.1

the Sideloader plugin seems not loading my mod files, and my `LogOutput.txt` got nothing output by Sideloader
```
[Info   :   BepInEx] Loading [Sideloader 12.3.1]
[Info   :   BepInEx] Loading [Slider Unlocker 12.3.1]
```
where it should output some log when loading mod files in 12.0.0.2
```
[Info   :   BepInEx] Loading [Sideloader 12.0.0.2]
[Info   :Sideloader] Scanning the "mods" directory...
[Info   :Sideloader] Loading mods from directory: C:\Users\Tidyzq\games\ai-test\AI-Syoujyo\mods
[Info   :Sideloader] List of loaded mods:
Loaded AI_UncensorSelector Base 1.0
Loaded [Female][SAC]UncensorSelectorPack_0.2.zip 0.2
Loaded Cur Male Uncensor 2.0

[Info   :Sideloader] Successfully loaded 3 mods out of 3 archives in 37ms
[Info   :   BepInEx] Loading [Slider Unlocker 12.3.1]
```

In the meantime, the config file for Sideloader plugin `com.bepis.bepinex.sideloader.cfg` is also not generated.

**Comment by 1458271** [comment]
Try to update your BepInExPlugins in Github. It was updated 5 days ago.

**Comment by ManlyMarco** [comment]
It's likely that there's some plugin conflict going on. The easiest way to get it fixed would be to install HF Patch and let it clean old mods https://github.com/ManlyMarco/AI-HF_Patch

**Comment by ManlyMarco** [comment]
Closed because of inactivity.
