### ISSUE TITLE
[Koikatsu VR] - [Sideloader loads ALL character mods on Free H launch]

### ISSUE THREAD

**Issue by ov3rh34t** [IllusionMods/BepisPlugins#90]
Sideloader seems to load every single mod for all characters in the character list when launching Free H in Koikatsu VR (Official).

I've noticed when playing regular Koikatsu, mods are only loaded when you actually start a H scene, the ones necessary for the selected characters only. Shouldn't this be a case in Koikatsu VR too?

How to reproduce:

1. Launch Koikatsu VR.
2. Select Free H.

What happens:
Every single mod is loaded resulting in a very very long loading time depending on how many characters you have in your character list.

**Comment by ManlyMarco** [comment]
There are special hooks to prevent this from happening in main game, no one added them for the VR module so far. There's no harm in this, just a bit slower loading time.

**Comment by ManlyMarco** [comment]
Fixed in https://github.com/IllusionMods/IllusionFixes/commit/4b4e24e3717c1c0ab6f643e31910484428e759bd
