### ISSUE TITLE
[AI] Screenshot plugin incompatible with HDRI background from DHH mod

### ISSUE THREAD

**Issue by thuanle2603** [IllusionMods/BepisPlugins#92]
![image](https://user-images.githubusercontent.com/56684477/71674553-0fbfaa00-2dae-11ea-9934-73ab0497fc69.png)
![image](https://user-images.githubusercontent.com/56684477/71674569-1e0dc600-2dae-11ea-9eeb-9e0ea45c99a3.png)
Incompatible with HDRI background from DHH mod.
The saved screenshot has black background.
I know that it's not caused by your mod but I hope you can take a look at this problem.

**Comment by ManlyMarco** [comment]
Fixed in #119
